### ISSUE TITLE
createLogger doesn't create log file path recursively

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-shared-core#60] opened 2017-11-06 14:18 UTC
More of a local debugging problem: Currently, if the `files` directory doesn't exist above `logs`, any package running `createLogger` will throw an exception.

Should probably use `fs-extra` and the `ensuredir` method

**Comment by justinneff** [comment] 2018-01-15 15:49
This is a duplicate of #19

**Closed by justinneff** 2018-01-15 15:49 UTC
Labels: bug, duplicate
